language: php
php:
  - 5.6
  - 5.5
  - 7.0
  - 7.1
  - 7.2
  - nightly
matrix:
  allow_failures:
    - php: 7.2
    - php: nightly
install:
  - travis_retry composer self-update && composer install
script:
  - vendor/bin/phpunit --testsuite "Zendesk API Unit Test Suites"
  - vendor/bin/phpcs --extensions=php --standard=PSR2 --report=summary -np src/ tests/
notifications:
  email: false
